name: Weather Data Scraper

on:
  push: # Run the workflow on any push to the repository
    branches:
      - main # Specify the branch to watch for pushes (e.g., main or master)
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas gspread oauth2client

      # Run the scraper
      - name: Run scraper
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python weather_scraper.py
